### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by ncoder-1** [hoytech/lmdbxx#4]
Any chance you could make a new release tag?  Last one is from 2015 and it would be convenient to have a specific version pulled  from a `CMakeLists.txt` file, instead of pulling master.

Thanks!

**Comment by hoytech** [comment]
Sure! Just tagged 0.9.21.0. I just took the latest version of LMDB I've tested against and added 0 at the end, which seems to be the original scheme.

**Comment by kallisti5** [comment]
Haiku  is now packaging this one.  Don't let it go abandoned like drycpp's version :-)

https://github.com/haikuports/haikuports/blob/master/dev-db/lmdbxx/lmdbxx-0.9.21.0.recipe

**Comment by hoytech** [comment]
I use this in several of my own projects, so plan on maintaining it indefinitely. Let me know if I can be of service. :+1:

**Comment by hoytech** [comment]
As noted in https://github.com/drycpp/lmdbxx/issues/28 it probably would've been better to increase the major version to signify that the API has changed. Sorry about that. Anyway I've now tagged 1.0.0 also.
