### ISSUE TITLE
lmdb::dbi::open should take a string_view

### ISSUE THREAD

**Issue by deepbluev7** [hoytech/lmdbxx#5]
If you store the names of sub dbs in a db, you need to first convert them to a std::string and then call c_str() on it, to be able to pass it safely to dbi::open. Imo it should be possible to pass the string_view directly.

This is a small UX fix, otherwise I really enjoy using this library, thank you for maintaining it!

**Comment by hoytech** [comment]
Good idea, thank you for requesting it! I just pushed a commit that I think should do what you want. Let me know if not :+1:

**Comment by deepbluev7** [comment]
Wow, awesome, thank you! That was super quick!
