### ISSUE TITLE
Test fails with MDB_BAD_TXN on OpenBSD

### ISSUE THREAD

**Issue by epsilon-0** [hoytech/lmdbxx#6]
The full error message is 

```
Failed with error: mdb_txn_begin: MDB_BAD_TXN: Transaction must abort, has a child, or is invalid
```

The error happens at https://github.com/hoytech/lmdbxx/blob/master/check.cc#L257

**Comment by hoytech** [comment]
Thanks for the report! What versions of OpenBSD and LMDB, and also which C++ compiler and version are you using?

**Comment by epsilon-0** [comment]
I am running OpenBSD -current (rolling release) with lmdb 0.9.29 and clang c++ compiler:
```
$ c++ --version
OpenBSD clang version 11.1.0
Target: amd64-unknown-openbsd6.9
Thread model: posix
InstalledDir: /usr/bin
```

**Comment by hoytech** [comment]
Hi! I fixed the test suite so it should now work on OpenBSD. There are some limitations to be aware of on this OS, though. Please see these docs I have just added.

https://github.com/hoytech/lmdbxx#openbsd

Thanks again for the report!

**Comment by epsilon-0** [comment]
thanks a lot!!
