### ISSUE TITLE
Move .h file to separate subdirectory

### ISSUE THREAD

**Issue by m5k8** [hoytech/lmdbxx#9]
Please consider moving `lmdb++.h` file to separate subdirectory. Currently it causes the following problems:
- I'm supplying the compiler with include path `somewhere/lib/lmdbxx`
- Then I do `#include <lmdb++.h>`
- Your `VERSION` file gets included from elsewhere (via `#include <version>`, Windows only problem, due to case insensitiveness), and causes compilation error.

I use your library via git subrepo, and moving `.h` file to my directory works against easy updates and duplication. Hardcoding path to `.h` file is also not too elegant, I'm passing tha path via CMake and compiler options.

Suggested method:
- lbdbxx subrepo path is `somewhere/lib/lmdbxx`
- .h file location is `somewhere/lib/lmdbxx/include/lbdbxx/lmdb++.h`
- include path for compiler is `somewhere/lib/lmdbxx/include`
- `#include <lmdbxx/lmdb++.h>`

And then the namespace of include files is not polluted with other random files and we also have more unique path for your include file.
That's currently very common pattern for include files.

**Comment by hoytech** [comment]
The reason it is in the root directory is because this is how I inherited it from the original version. In my own libraries I typically follow the layout you describe.

What I'm thinking to do is move the file to where you describe, but add a symlink from the original file's location to the new one so people's builds don't break.

**Comment by hoytech** [comment]
This should be done in commit fac973b01ed69bd084b302151699929f0a77b769 - let me know if you have any issues, thanks!

**Comment by m5k8** [comment]
No issues, it's fine! Thank you!
